--ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-96HACDB\Hp];


--GO
--ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


--GO
--ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

